const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    },
    {
      _id: '2',
      name: 'Adidas Slim Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 20,
      brand: 'Adidas',
      rating: 2,
      numReviews: 10,
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    },
    {
      _id: '3',
      name: 'Puma Slim Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 0,
      brand: 'Puma',
      rating: 4.8,
      numReviews: 10,
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    },
    {
      _id: '4',
      name: 'Nike Slim Pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 15,
      brand: 'Nike',
      rating: 3,
      numReviews: 14,
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    },
    {
      _id: '5',
      name: 'Puma Slim Pants',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 25,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 14,
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    },
    {
      _id: '6',
      name: 'Adidas Slim Pants',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 90,
      countInStock: 5,
      brand: 'Adidas',
      rating: 5,
      numReviews: 14,
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing',
    },
  ],
};

export default data;
